### ISSUE TITLE
Eliminate the need for users to register/login

### ISSUE THREAD

**Issue by revgum** [osulp/Easydeposit2#117]
### Descriptive summary

When a potential author is emailed, the link should bypass and user registration/login and give the person the ability to immediately attach file(s) to a publication and publish the work.

### Expected behavior

- User is emailed a recruitment email with a link to 'claim' the publication
- User clicks link in the email
- Publication page is displayed, user is able to upload files and publish

### Implementation behavior

- [x] User records are created as authors are fetched from WOS or the OSU API. See #162
- [x] AuthorPublication records relate to a user identified by the email address. See #164
- [x] AuthorPublication records contain a GUID for the recruitment email. See #161 
- [x] before_action on the publication controller to fetch the user and publication See #163

**Comment by zhang4952** [comment]
fixed
