### ISSUE TITLE
Easydeposit2 features

### ISSUE THREAD

**Issue by zhang4952** [osulp/Easydeposit2#38]
This is a place used to collect/finalize required features of ED2. 
ED2 will be a standalone application, rather than a backend rake task to feed data into SA, for several benefits:
- Librarians can see the new publications and take actions accordingly like send email, delete, or save. 
- Allow other interested parties, like Research Office staff, to access the harvested records.

**ED2 features**
- ED2 will query WoS index with WoS API to find all articles published in the past 4weeks with 'Oregon State University' as affiliation.
- Contact authors who are OSU affiliated or co-authored with OSU faculty will receive email notification to deposit their fulltext manuscripts with a deposit link pointing to ED2:
             - the link destination is the WoS record page in ED2 with harvested metadata.
             - the author uploads the fulltext manuscript (authentication required and ED2 does not offer curation function).
             - record saved in ED2 with new information and the complete record is ingested into SA.
- authorized person (via OSU CAS) is privileged to see the full list of harvested publication, select publications, and choose actions like: 
             - select email address and and send article recruiting email
             - delete records 
             - deposit records (metadata only) to SA
- ED2 should provide these analytics to SA
             - how many OA articles in SA are self-deposited (by faculty) or from the workflow of ED2.
             - how many ED2 harvested publications are deposited in SA as OA with full-text.
- ED2 won't provide any editing capacity to harvested publications

**Comment by zhang4952** [comment]
Related issues will be added here.

**Comment by zhang4952** [comment]
ED2 Development milestones
Preparation

- [ ] apply account for Web of Science SearchLite and Article Match Retrieval

- [ ] setup staging environment for ED2

Phase 1

- [ ] retrieve OSU publications from WoS

- [ ] save OSU publications to ED2 local DB

- [ ] show publications in view

Phase 2

- [ ] save retrieved OSU publication to SA@OSU as metadata only works

- [ ] link ED2 publications with created SA@OSU works

Phase 3

- [ ] parse author email from WoS 

- [ ] save email in ED2 DB and create a deposit soliciting email

- [ ] setup production and deploy

**Comment by revgum** [comment]
These are all addressed in current epic and related tickets.
